### Register
POST http://localhost:5000/register

{
  "name":"Nursandy Ihksan",
  "email":"sandy@gmail.com",
  "password": "12345678"
}

### Login
POST http://localhost:5000/login

{
  "email":"sandy@gmail.com",
  "password": "12345678"
}

### Logout
GET http://localhost:5000/logout

### GET ALL PRODUCTS
GET http://localhost:5000/api/products